"""Expand Job model

Revision ID: 0c8edfedf4d5
Revises: 
Create Date: 2026-08-02 19:35:04.389076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8edfedf4d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


"""Expand Job model

Revision ID: 0c8edfedf4d5
Revises: 
Create Date: 2026-08-02 19:35:04.389076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8edfedf4d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_posting_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('jobs', sa.Column('additional_information', sa.Text(), nullable=True))
    op.alter_column('jobs', 'linkedin_posted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_linkedin_accounts_id'), 'linkedin_accounts', ['id'], unique=False)
    op.drop_constraint(op.f('uq_job_account'), 'linkedin_posts', type_='unique')
    op.create_index(op.f('ix_linkedin_posts_id'), 'linkedin_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkedin_posts_id'), table_name='linkedin_posts')
    op.create_unique_constraint(op.f('uq_job_account'), 'linkedin_posts', ['job_id', 'linkedin_account_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_linkedin_accounts_id'), table_name='linkedin_accounts')
    op.alter_column('jobs', 'linkedin_posted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('jobs', 'additional_information')
    op.drop_column('jobs', 'job_posting_date')
    # ### end Alembic commands ###


def downgrade():

    op.alter_column(
        'jobs',
        'linkedin_posted',
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text('false')
    )

    op.drop_column(
        'jobs',
        'additional_information'
    )

    op.drop_column(
        'jobs',
        'job_posting_date'
    )