"""Add vendor partnership tables

Revision ID: b4d3612ccf96
Revises: 0c8edfedf4d5
Create Date: 2026-08-10 12:24:43.304639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d3612ccf96'
down_revision: Union[str, Sequence[str], None] = '0c8edfedf4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_hashtags_id'), 'vendor_hashtags', ['id'], unique=False)
    op.create_table('vendor_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_images_id'), 'vendor_images', ['id'], unique=False)
    op.create_table('vendor_post_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkedin_account_id', sa.Integer(), nullable=False),
    sa.Column('linkedin_post_id', sa.String(length=255), nullable=True),
    sa.Column('post_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['linkedin_account_id'], ['linkedin_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_post_history_id'), 'vendor_post_history', ['id'], unique=False)
    op.create_table('vendor_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('posting_time', sa.String(length=10), nullable=False),
    sa.Column('active_image_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['active_image_id'], ['vendor_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_settings_id'), 'vendor_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_settings_id'), table_name='vendor_settings')
    op.drop_table('vendor_settings')
    op.drop_index(op.f('ix_vendor_post_history_id'), table_name='vendor_post_history')
    op.drop_table('vendor_post_history')
    op.drop_index(op.f('ix_vendor_images_id'), table_name='vendor_images')
    op.drop_table('vendor_images')
    op.drop_index(op.f('ix_vendor_hashtags_id'), table_name='vendor_hashtags')
    op.drop_table('vendor_hashtags')
    # ### end Alembic commands ###
